[build]
  command = ""
  publish = "public"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
